//
// Created by xisisu on 9/19/16.
//

/*
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */

#include <iostream>
#include <vector>

class Solution {
public:
    char findTheDifference(std::string s, std::string t) {
        // since all stuff are lower case, use 26 size array is enough
        int array[26];
        for (int i = 0; i < 26; ++i) { array[i] = 0; }
        for (auto const &c : s) { ++array[c-'a']; }
        for (auto const &c : t) {
            if (--array[c-'a'] < 0) { return c; }
        }
        return -1;
    }
};

int main() {
    Solution sol;
    std::vector<std::pair<std::string, std::string>> tests = {
            {"", "a"}
            , {"abcd", "abcde"}
    };

    for (auto const &test : tests) {
        std::cout << test.first << ", " << test.second << ": " << sol.findTheDifference(test.first, test.second) << std::endl;
    }

    return 0;
}